[target.x86_64-unknown-linux-musl]
image = "ghcr.io/rust-cross/rust-musl-cross:x86_64-musl"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [
  "apt-get update && apt-get install --assume-yes --no-install-recommends software-properties-common ca-certificates gnupg",
  "add-apt-repository --yes ppa:ubuntu-toolchain-r/test",
  "apt-get update && apt-get install --assume-yes --no-install-recommends g++-12-aarch64-linux-gnu"
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CC_aarch64_unknown_linux_gnu",
  "CXX_aarch64_unknown_linux_gnu",
  "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER"
]
